# Generated by Django 3.2.7 on 2021-11-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='product',
            field=models.CharField(max_length=50),
        ),
    ]
