# Generated by Django 3.2.9 on 2021-12-01 21:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=50)),
                ('base_offer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_starting', models.DateTimeField(default=datetime.date.today)),
                ('time_ending', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('offer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_time', models.DateTimeField(default=datetime.date.today)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
