# Generated by Django 3.2.9 on 2021-12-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_auction_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='time_ending',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='auction',
            name='time_starting',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
