# Generated by Django 3.2.7 on 2021-11-19 02:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=60, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=60, verbose_name='Lastname')),
                ('username', models.CharField(max_length=45, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('isadmi', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product', models.IntegerField()),
                ('time_starting', models.DateTimeField(default=datetime.date.today)),
                ('time_ending', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bid_time', models.DateTimeField(default=datetime.date.today)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApi.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApi.user')),
            ],
        ),
    ]
