from .userViews                import UserCreateView
from .userViews                import UserDetailView
from .userViews                import UserUpdateView
from .userViews                import UserDeleteView
from .verifyTokenView          import VerifyTokenView
from .myTokenObtainPairView    import MyTokenObtainPairView
from .bidViews                 import BidCreateview,BidDetailView,BidTopView,BidDeleteview
from .auctionViews             import AuctionCreateview,AuctionUpdateView
from .auctionViews             import AuctionDeleteView,AuctionDetailView,AuctionListView
